projects:
  fundshelter:
    schemaPath: src/graphql/schema.json
    includes:
      - gql/db
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: gql
extensions:
  amplify:
    version: 3
